### ISSUE TITLE
Relations

### ISSUE THREAD

**Issue by jojovem** [faisalarbain/decouple-entitiy-from-eloquent#1]
It would be nice to see how relations would work in your idea!
I really like the approach!
Ty

**Comment by faisalarbain** [comment]
Hi @jojovem , thanks for the comment. 
to persist value objects usually depends on case by case. simple case usually I just persist the object in json string. 

in more complex scenario, I use events to identify which eloquent model needs to be update. this is nice, as I can also persist my events as well.

if the scenario is extremely complex, then i will review my modelling and check if i miss any concept.
